#ifndef PUBLIC_H
#define PUBLIC_H

#define BUFSIZE 8192
#define AUDIO_FILE_TYPE 32
#define BEGINPORT 34509
#define ENDPORT 34608
#define RECORD_PATH "/tmp/record.mp3"
#define FIRMWARE_PATH "/var/run/SONICCOREV100R001.bin"

enum {
    TCPNETWORKSET = 101,
    UPDATEPWD,
    NETWORKSET,
    LOGIN,
    SETDEVICEADDRRESS,
    AUDIOPLAY,
    AUDIOSTOP,
    VOLUMSET,
    REBOOT,
    GETDEVICESTATUS,
    TTSPLAY,
    LIGHTSWITCH,
    FILEUPLOAD,
    RESTORE,
    AUDIONUMORTPLAY,
    TTSNUMORTPLAY,
    GETDEVICEBASEINFO,
    RECORD,
    REMOTEUPGRADE,
    GETAUDIOLIST,
    LIGHTCONFIG,
    RECORDBEGIN,
    RECORDEND,
    AUDIOFILEUPLOAD,
    REMOTEFILEUPGRADE,
    DSPMANAGE
};

const char *const OPERATION_FAIL_ERROR = "F5";
const char *const TCP_TIMEOUT = "F71";
const char *const NONSUPPORT_ERROR = "F4";
const char *const RECORD_SIZE_ERROR = "F62";
const char *const TCP_TRANSFER_ERROR = "F66";

#endif // PUBLIC_H